### ISSUE TITLE
Ford Algorithm edge 개수 에러?

### ISSUE THREAD

**Issue by hank110** [lovit/lovit.github.io#2]
"Ford algorithm 을 이용한 최단 경로 탐색" 포스트를 보면,
지하철 노선도 예시가 26개의 edge로 구성되어 있다고 쓰여있네요.

다만, graph 이론 상 edge의 정의를 보면 (http://www.cs.yale.edu/homes/aspnes/pinewiki/GraphTheory.html 참고)

".. In particular, unless otherwise specified, a graph will refer to a simple undirected graph: an undirected graph where each edge connects two distinct vertices (thus no self-loops) and **there is at most one edge between each pair of vertices (no parallel edges).**"

노드 쌍에서 정의될 수 있는 최대 edge의 개수는 1개라고 합니다.
그렇다면 예시 내 edge의 수는 26개가 아닌 13개가 되어야 하는게 아닐까 궁금합니다.
(만약 그렇다면 edge count 하는 코드 또한 수정이 필요하지 않을까 싶네요)

**Comment by lovit** [comment]
Undirected graph 는 양 방향에 동일한 weight 를 주는 directed graph 로 볼 수 있기 때문에 13 * 2 개인 26 개로 정의하였습니다.
